Repository Icinga/ipl-html, pull requests merged in 2022-12, with the labels that each got.

#92 Fix too early wrapper loop detection
  src/HtmlDocument.php
  tests/HtmlDocumentTest.php
Labels: bug, cla/signed

#93 Fix incorrect rendered by reset
  src/HtmlDocument.php
  tests/HtmlDocumentTest.php
Labels: bug, cla/signed

#97 Don't cache element validation state
  src/FormDecorator/DdDtDecorator.php
  src/FormDecorator/DivDecorator.php
  src/FormElement/BaseFormElement.php
  src/FormElement/SelectElement.php
Labels: cla/signed

#68 FormElement: Add `RadioElement`
  src/FormElement/RadioElement.php
  src/FormElement/RadioOption.php
  tests/FormElement/RadioElementTest.php
Labels: enhancement, cla/signed
