Repository Icinga/ipl-html, pull requests merged in 2023-01, with the labels that each got.

#102 Update Checkout Action to v3
  .github/workflows/php.yml
Labels: cla/signed

#88 Enhance select element
  src/Common/MultipleAttribute.php
  src/FormElement/SelectElement.php
  src/FormElement/SelectOption.php
  tests/DocumentationFormsTest.php
  tests/FormElement/SelectElementTest.php
Labels: enhancement, cla/signed

#104 Fix empty select value attribute
  src/FormElement/SelectOption.php
  tests/DocumentationFormsTest.php
  tests/FormElement/SelectElementTest.php
Labels: bug, cla/signed

#105 PHP 8.2 Support
  .github/workflows/php.yml
Labels: cla/signed

#74 Replace SubFormElement with FieldsetElement
  src/Contract/FormElementDecorator.php
  src/FormDecorator/DivDecorator.php
  src/FormElement/BaseFormElement.php
  src/FormElement/CheckboxElement.php
  src/FormElement/FieldsetElement.php
  src/FormElement/RadioElement.php
  src/FormElement/SubFormElement.php
  tests/FormElement/FieldsetElementTest.php
  tests/FormElement/SubFormElementTest.php
Labels: enhancement, cla/signed

#106 Attribute: Allow separator customization
  src/Attribute.php
  tests/AttributeTest.php
Labels: enhancement, cla/signed

#66 FormElement: Add `FileElement`
  composer.json
  src/Form.php
  src/FormElement/FileElement.php
  tests/FormElement/FileElementTest.php
  tests/Lib/FileElementWithAdjustableConfig.php
Labels: enhancement, cla/signed
