Repository Icinga/ipl-html, pull requests merged in 2024-06, with the labels that each got.

#135 Phpstan: Separate workflow
  .github/workflows/php.yml
  .github/workflows/phpstan.yml
  phpstan.neon
Labels: enhancement, cla/signed

#137 FieldsetElement: Correctly handle elements with multiple values
  src/FormElement/FieldsetElement.php
  tests/FormElement/FieldsetElementTest.php
Labels: bug, cla/signed

#139 Catch `\Throwable` instead of `\Exception`
  src/DeferredText.php
  src/Form.php
  src/FormattedString.php
  src/HtmlDocument.php
  src/Text.php
Labels: cla/signed
